/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.server;

import java.util.LinkedList;
import utils.observerpattern.IObservable;
import utils.observerpattern.IObserver;

/**
 *
 * @author alexander
 */
public class Server extends javax.swing.JFrame implements IObservable {
    
    LinkedList<IObserver> observers;

    /**
     * Creates new form Server
     */
    public Server() {
        initComponents();
        observers = new LinkedList<>();
        
        this.setTitle("Server");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessages = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMessages.setColumns(20);
        txtMessages.setRows(5);
        jScrollPane1.setViewportView(txtMessages);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMessages;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean addObserver(IObserver pObserver) {
        return observers.add(pObserver);
    }
    
    @Override
    public boolean removeObserver(IObserver pObserver) {
        return observers.remove(pObserver);
    }

    @Override
    public boolean update(IObserver pObserver, Object pMessage) {
        int pos = observers.indexOf(pObserver);
        
        if (pos != -1) {
            observers.get(pos).update(pMessage);
            return true;
        }
        
        return false;
    }

    @Override
    public void updateAll(Object pMessage) {
        for (IObserver observer : observers) {
            observer.update(pMessage);
        }
    }
}
