/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.player;

import java.util.LinkedList;
import utils.observerpattern.IObservable;
import utils.observerpattern.IObserver;
import vista.player.drag.DragListener;

/**
 *
 * @author alexander
 */
public class SpellsDeck extends javax.swing.JFrame implements IObservable {
    
    LinkedList<IObserver> observers;

    /**
     * Creates new form SpellsDeck
     */
    public SpellsDeck() {
        initComponents();
        observers = new LinkedList<>();
        
        this.setTitle("Spells Deck");
        
        DragListener dragListener = new DragListener();
        
        addMouseListener(dragListener);
        addMouseMotionListener(dragListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCard0 = new javax.swing.JLabel();
        lblCard1 = new javax.swing.JLabel();
        lblCard2 = new javax.swing.JLabel();
        lblCard3 = new javax.swing.JLabel();
        lblCard4 = new javax.swing.JLabel();
        lblCard5 = new javax.swing.JLabel();
        lblCard6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCardSelected0 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCardSelected1 = new javax.swing.JLabel();
        lblCardSelected2 = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        lblGanada2 = new javax.swing.JLabel();
        lblGanada1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSecretWord = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblEnemyCard0 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEnemyCard1 = new javax.swing.JLabel();
        lblEnemyCard2 = new javax.swing.JLabel();
        lblPerdido1 = new javax.swing.JLabel();
        lblPerdid2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCard0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card0.jpg"))); // NOI18N
        lblCard0.setText("0");
        lblCard0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCard0.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCard0.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCard0.setPreferredSize(new java.awt.Dimension(208, 302));

        lblCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card1.jpg"))); // NOI18N
        lblCard1.setText("1");
        lblCard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCard1.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCard1.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCard1.setPreferredSize(new java.awt.Dimension(208, 302));

        lblCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card2.jpg"))); // NOI18N
        lblCard2.setText("2");
        lblCard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCard2.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCard2.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCard2.setPreferredSize(new java.awt.Dimension(208, 302));

        lblCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card3.jpg"))); // NOI18N
        lblCard3.setText("3");
        lblCard3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCard3.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCard3.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCard3.setPreferredSize(new java.awt.Dimension(208, 302));

        lblCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card4.jpg"))); // NOI18N
        lblCard4.setText("4");
        lblCard4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCard4.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCard4.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCard4.setPreferredSize(new java.awt.Dimension(208, 302));

        lblCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card5.jpg"))); // NOI18N
        lblCard5.setText("5");
        lblCard5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCard5.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCard5.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCard5.setPreferredSize(new java.awt.Dimension(208, 302));

        lblCard6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card6.jpg"))); // NOI18N
        lblCard6.setText("6");
        lblCard6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCard6.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCard6.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCard6.setPreferredSize(new java.awt.Dimension(208, 302));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCardSelected0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCardSelected0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCardSelected0.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCardSelected0.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCardSelected0.setPreferredSize(new java.awt.Dimension(208, 302));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Deck seleccionado:");

        lblCardSelected1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCardSelected1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCardSelected1.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCardSelected1.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCardSelected1.setPreferredSize(new java.awt.Dimension(208, 302));

        lblCardSelected2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCardSelected2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCardSelected2.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCardSelected2.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCardSelected2.setPreferredSize(new java.awt.Dimension(208, 302));

        btnJugar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnJugar.setText("A jugar!!!");

        lblGanada2.setMaximumSize(new java.awt.Dimension(50, 50));
        lblGanada2.setMinimumSize(new java.awt.Dimension(50, 50));
        lblGanada2.setPreferredSize(new java.awt.Dimension(50, 50));

        lblGanada1.setMaximumSize(new java.awt.Dimension(50, 50));
        lblGanada1.setMinimumSize(new java.awt.Dimension(50, 50));
        lblGanada1.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel3.setText("Palabra secreta:");

        txtSecretWord.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnSave.setText("Guardar en un archivo");

        jLabel4.setText("Mensajes");

        lblMessage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGanada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGanada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCardSelected0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCardSelected1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCardSelected2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSecretWord)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSave))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCardSelected0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGanada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGanada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCardSelected1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCardSelected2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSecretWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnJugar)))))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEnemyCard0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEnemyCard0.setMaximumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard0.setMinimumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard0.setPreferredSize(new java.awt.Dimension(208, 302));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Deck enemigo:");

        lblEnemyCard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEnemyCard1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEnemyCard1.setMaximumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard1.setMinimumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard1.setPreferredSize(new java.awt.Dimension(208, 302));

        lblEnemyCard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEnemyCard2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEnemyCard2.setMaximumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard2.setMinimumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard2.setPreferredSize(new java.awt.Dimension(208, 302));

        lblPerdido1.setMaximumSize(new java.awt.Dimension(50, 50));
        lblPerdido1.setMinimumSize(new java.awt.Dimension(50, 50));
        lblPerdido1.setPreferredSize(new java.awt.Dimension(50, 50));

        lblPerdid2.setMaximumSize(new java.awt.Dimension(50, 50));
        lblPerdid2.setMinimumSize(new java.awt.Dimension(50, 50));
        lblPerdid2.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPerdid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPerdido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEnemyCard0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEnemyCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEnemyCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEnemyCard0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPerdido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPerdid2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEnemyCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnemyCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCard0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCard0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    public boolean addObserver(IObserver pObserver) {
        return observers.add(pObserver);
    }
    
    @Override
    public boolean removeObserver(IObserver pObserver) {
        return observers.remove(pObserver);
    }

    @Override
    public boolean update(IObserver pObserver, Object pMessage) {
        int pos = observers.indexOf(pObserver);
        
        if (pos != -1) {
            observers.get(pos).update(pMessage);
            return true;
        }
        
        return false;
    }

    @Override
    public void updateAll(Object pMessage) {
        for (IObserver observer : observers) {
            observer.update(pMessage);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCard0;
    private javax.swing.JLabel lblCard1;
    private javax.swing.JLabel lblCard2;
    private javax.swing.JLabel lblCard3;
    private javax.swing.JLabel lblCard4;
    private javax.swing.JLabel lblCard5;
    private javax.swing.JLabel lblCard6;
    private javax.swing.JLabel lblCardSelected0;
    private javax.swing.JLabel lblCardSelected1;
    private javax.swing.JLabel lblCardSelected2;
    private javax.swing.JLabel lblEnemyCard0;
    private javax.swing.JLabel lblEnemyCard1;
    private javax.swing.JLabel lblEnemyCard2;
    private javax.swing.JLabel lblGanada1;
    private javax.swing.JLabel lblGanada2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPerdid2;
    private javax.swing.JLabel lblPerdido1;
    private javax.swing.JTextField txtSecretWord;
    // End of variables declaration//GEN-END:variables
}
