/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.player;

import java.util.HashMap;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.socketspellsdeck.message.IMessage;
import model.socketspellsdeck.message.MessageFactory;
import utils.Constants;
import utils.Logger;
import utils.OS;
import utils.observerpattern.IObservable;
import utils.observerpattern.IObserver;
import vista.player.drag.DragListener;

/**
 *
 * @author alexander
 */
public class SpellsDeck extends javax.swing.JFrame implements IObservable {
    
    private final LinkedList<IObserver> observers;
    private final HashMap componentMap;
    private final ImageIcon winImage;
    private final ImageIcon loseImage;

    /**
     * Creates new form SpellsDeck
     */
    public SpellsDeck() {
        initComponents();
        observers = new LinkedList<>();
        
        this.setTitle("Spells Deck");
        
        DragListener dragListener = new DragListener();
        
        addMouseListener(dragListener);
        addMouseMotionListener(dragListener);
        
        // Se cargan las imágenes de cuando se gana un match y cuando se pierde.
        String winImagePath = ClassLoader.getSystemResource("vista/images/win.png").getFile();
        if (OS.isWindows()) {
            winImagePath = winImagePath.substring(1);
        }
        winImage = new ImageIcon(winImagePath);
        String loseImagePath = ClassLoader.getSystemResource("vista/images/loos.png").getFile();
        if (OS.isWindows()) {
            loseImagePath = loseImagePath.substring(1);
        }
        loseImage = new ImageIcon(loseImagePath);
        
        // Crea un HashMap de componentes de la ventana
        //createComponentMap();
        componentMap = new HashMap<>();
        componentMap.put("lblCard0", lblCard0);
        componentMap.put("lblCard1", lblCard1);
        componentMap.put("lblCard2", lblCard2);
        componentMap.put("lblCard3", lblCard3);
        componentMap.put("lblCard4", lblCard4);
        componentMap.put("lblCard5", lblCard5);
        componentMap.put("lblCard6", lblCard6);
        componentMap.put("lblCardSelected0", lblCardSelected0);
        componentMap.put("lblCardSelected1", lblCardSelected1);
        componentMap.put("lblCardSelected2", lblCardSelected2);
        componentMap.put("lblEnemyCard0", lblEnemyCard0);
        componentMap.put("lblEnemyCard1", lblEnemyCard1);
        componentMap.put("lblEnemyCard2", lblEnemyCard2);
        componentMap.put("lblGanado1", lblGanado1);
        componentMap.put("lblGanado2", lblGanado2);
        componentMap.put("lblPerdido1", lblPerdido1);
        componentMap.put("lblPerdido2", lblPerdido2);
        componentMap.put("txtSecretKey", txtSecretKey);
        componentMap.put("lblMessage", lblMessage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCard0 = new javax.swing.JLabel();
        lblCard1 = new javax.swing.JLabel();
        lblCard2 = new javax.swing.JLabel();
        lblCard3 = new javax.swing.JLabel();
        lblCard4 = new javax.swing.JLabel();
        lblCard5 = new javax.swing.JLabel();
        lblCard6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCardSelected0 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCardSelected1 = new javax.swing.JLabel();
        lblCardSelected2 = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        lblGanado2 = new javax.swing.JLabel();
        lblGanado1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSecretKey = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblEnemyCard0 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEnemyCard1 = new javax.swing.JLabel();
        lblEnemyCard2 = new javax.swing.JLabel();
        lblPerdido1 = new javax.swing.JLabel();
        lblPerdido2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCard0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card0.jpg"))); // NOI18N
        lblCard0.setText("0");
        lblCard0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card1.jpg"))); // NOI18N
        lblCard1.setText("1");
        lblCard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card2.jpg"))); // NOI18N
        lblCard2.setText("2");
        lblCard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card3.jpg"))); // NOI18N
        lblCard3.setText("3");
        lblCard3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card4.jpg"))); // NOI18N
        lblCard4.setText("4");
        lblCard4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card5.jpg"))); // NOI18N
        lblCard5.setText("5");
        lblCard5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCard6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/Card6.jpg"))); // NOI18N
        lblCard6.setText("6");
        lblCard6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCard6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCardSelected0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCardSelected0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCardSelected0.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCardSelected0.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCardSelected0.setPreferredSize(new java.awt.Dimension(208, 302));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Deck seleccionado:");

        lblCardSelected1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCardSelected1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCardSelected1.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCardSelected1.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCardSelected1.setPreferredSize(new java.awt.Dimension(208, 302));

        lblCardSelected2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCardSelected2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCardSelected2.setMaximumSize(new java.awt.Dimension(208, 302));
        lblCardSelected2.setMinimumSize(new java.awt.Dimension(208, 302));
        lblCardSelected2.setPreferredSize(new java.awt.Dimension(208, 302));

        btnJugar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnJugar.setText("A jugar!!!");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        lblGanado2.setMaximumSize(new java.awt.Dimension(50, 50));
        lblGanado2.setMinimumSize(new java.awt.Dimension(50, 50));
        lblGanado2.setPreferredSize(new java.awt.Dimension(50, 50));

        lblGanado1.setMaximumSize(new java.awt.Dimension(50, 50));
        lblGanado1.setMinimumSize(new java.awt.Dimension(50, 50));
        lblGanado1.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel3.setText("Palabra secreta:");

        txtSecretKey.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtSecretKey.setFocusable(false);

        btnSave.setText("Guardar en un archivo");

        jLabel4.setText("Mensajes");

        lblMessage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblMessage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGanado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGanado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCardSelected0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCardSelected1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCardSelected2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSecretKey)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSave))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCardSelected0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGanado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGanado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCardSelected1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCardSelected2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSecretKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnJugar)))))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEnemyCard0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEnemyCard0.setMaximumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard0.setMinimumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard0.setPreferredSize(new java.awt.Dimension(208, 302));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Deck enemigo:");

        lblEnemyCard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEnemyCard1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEnemyCard1.setMaximumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard1.setMinimumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard1.setPreferredSize(new java.awt.Dimension(208, 302));

        lblEnemyCard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEnemyCard2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEnemyCard2.setMaximumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard2.setMinimumSize(new java.awt.Dimension(208, 302));
        lblEnemyCard2.setPreferredSize(new java.awt.Dimension(208, 302));

        lblPerdido1.setMaximumSize(new java.awt.Dimension(50, 50));
        lblPerdido1.setMinimumSize(new java.awt.Dimension(50, 50));
        lblPerdido1.setPreferredSize(new java.awt.Dimension(50, 50));

        lblPerdido2.setMaximumSize(new java.awt.Dimension(50, 50));
        lblPerdido2.setMinimumSize(new java.awt.Dimension(50, 50));
        lblPerdido2.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPerdido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPerdido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEnemyCard0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEnemyCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEnemyCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEnemyCard0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPerdido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPerdido2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEnemyCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnemyCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCard0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCard1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCard2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCard3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCard4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCard5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCard6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCard5)
                        .addComponent(lblCard4)
                        .addComponent(lblCard6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCard0)
                        .addComponent(lblCard1)
                        .addComponent(lblCard2)
                        .addComponent(lblCard3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        
       if (!("".equals(lblCardSelected0.getText()) || "".equals(lblCardSelected1.getText()) || "".equals(lblCardSelected2.getText())) 
               && !(lblCardSelected0.getText().equals(lblCardSelected1.getText()) || lblCardSelected0.getText().equals(lblCardSelected2.getText()) || lblCardSelected1.getText().equals(lblCardSelected2.getText()))) {
           this.updateAll(MessageFactory.createMessage("", IMessage.TIPO.MESSAGE_FROM_CLIENT, MessageFactory.TIPO_MENSAJE.SELECT_DECK.toString() + "," + lblCardSelected0.getText() + "," + lblCardSelected1.getText() + "," + lblCardSelected2.getText()));
           for (int pos = 0; pos < Constants.MAX_SELECTED_CARDS_NUMBER; pos ++) {
               ((JLabel)getComponentByName("lblCardSelected" + pos)).setIcon(((JLabel)getComponentByName("lblCard" + ((JLabel)getComponentByName("lblCardSelected" + pos)).getText())).getIcon());
           }
       } else {
           JOptionPane.showMessageDialog(this, "El deck debe contener tres cartas distintas.", "Error", JOptionPane.OK_OPTION);
       }
    }//GEN-LAST:event_btnJugarActionPerformed
    
    @Override
    public boolean addObserver(IObserver pObserver) {
        return observers.add(pObserver);
    }
    
    @Override
    public boolean removeObserver(IObserver pObserver) {
        return observers.remove(pObserver);
    }

    @Override
    public boolean update(IObserver pObserver, Object pMessage) {
        int pos = observers.indexOf(pObserver);
        
        if (pos != -1) {
            observers.get(pos).update(pMessage);
            return true;
        }
        
        return false;
    }

    @Override
    public void updateAll(Object pMessage) {
        for (IObserver observer : observers) {
            observer.update(pMessage);
        }
    }
    
    public void print(String pMessage) {
        lblMessage.setText(pMessage);
    }
    
    public void eraseEnemyCards() {
        lblEnemyCard0.setText("");
        lblEnemyCard0.setIcon(null);
        lblEnemyCard1.setText("");
        lblEnemyCard1.setIcon(null);
        lblEnemyCard2.setText("");
        lblEnemyCard2.setIcon(null);
    }
    
    public void writeKey (String pKey) {
        txtSecretKey.setText(pKey);
    }
    
    public void fadeMyCard(int pPosCard) {
        fadeCard("lblCardSelected" + pPosCard);
    }
    
    public void fadeEnemyCard(int pPosCard) {
        fadeCard("lblEnemyCard" + pPosCard);
    }
    
    public void fadeCard(String pComponentName) {
        Logger.Log("SpellsDeck: " + "Oscurecemos la tarjeta en el componente: " + pComponentName);
        JLabel selectedCard = (JLabel)this.getComponentByName(pComponentName);
        String iconPath = selectedCard.getIcon().toString();
        String newIconPath = iconPath.substring(5, iconPath.length() - 4) + "Faded" + iconPath.substring(iconPath.length() - 4);
        Logger.Log("SpellsDeck: " + "Nuevo ícono path: " + newIconPath);
        selectedCard.setIcon(new ImageIcon(newIconPath));
    }
    
    public int[] getSelectedCards(){
        int[] selectedCards = new int[3];
        for (int pos = 0; pos < Constants.MAX_SELECTED_CARDS_NUMBER; pos++) {
            selectedCards[pos] = Integer.parseInt(((JLabel)getComponentByName("lblCardSelected" + pos)).getText());
        }
        return selectedCards;
    }
    
    public void setEnemySelectedCards(int[] pSelectedCards){
        for (int pos = 0; pos < Constants.MAX_SELECTED_CARDS_NUMBER; pos++) {
            JLabel lblEnemy = (JLabel)getComponentByName("lblEnemyCard" + pos);
            JLabel lblEnemySelected = (JLabel)getComponentByName("lblCard" + pSelectedCards[pos]);
            lblEnemy.setIcon(lblEnemySelected.getIcon());
            lblEnemy.setText(lblEnemySelected.getText());
        }
    }
    
    /*private void createComponentMap() {
        componentMap = new HashMap<>();
        Component[] components = this.getContentPane().getComponents();
        for (int i=0; i < components.length; i++) {
                componentMap.put(components[i].getName(), components[i]);
        }
    }*/
    
    public void winMatch() {
        if (lblGanado1.getIcon() != null) {
            lblGanado1.setIcon(winImage);
            lblPerdido1.setIcon(loseImage);
        } else {
            lblGanado2.setIcon(winImage);
            lblPerdido2.setIcon(loseImage);
        }
    }
    
    public void loseMatch() {
        if (lblGanado1.getIcon() != null) {
            lblGanado1.setIcon(loseImage);
            lblPerdido1.setIcon(winImage);
        } else {
            lblGanado2.setIcon(loseImage);
            lblPerdido2.setIcon(winImage);
        }
    }

    public Object getComponentByName(String name) {
        // Logger.Log("SpellsDeck: Buscando el componente: " + name + ", está?: " + componentMap.containsKey(name));
        if (componentMap.containsKey(name)) {
                return componentMap.get(name);
        } else {
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCard0;
    private javax.swing.JLabel lblCard1;
    private javax.swing.JLabel lblCard2;
    private javax.swing.JLabel lblCard3;
    private javax.swing.JLabel lblCard4;
    private javax.swing.JLabel lblCard5;
    private javax.swing.JLabel lblCard6;
    private javax.swing.JLabel lblCardSelected0;
    private javax.swing.JLabel lblCardSelected1;
    private javax.swing.JLabel lblCardSelected2;
    private javax.swing.JLabel lblEnemyCard0;
    private javax.swing.JLabel lblEnemyCard1;
    private javax.swing.JLabel lblEnemyCard2;
    private javax.swing.JLabel lblGanado1;
    private javax.swing.JLabel lblGanado2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPerdido1;
    private javax.swing.JLabel lblPerdido2;
    private javax.swing.JTextField txtSecretKey;
    // End of variables declaration//GEN-END:variables
}
